name: Linter

on: [push, pull_request]

jobs:
  es-linter-for-ts:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 14
  
    - name: Install dependencies
      run: |
        cd setup/dashboard/ws || exit 1
        npm ci

    - name: Run linter
      run: |
          cd setup/dashboard/ws || exit 1
          npm run lint

  es-linter-for-js:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 14
  
    - name: Install dependencies
      run: |
        cd setup/dashboard || exit 1
        npm ci

    - name: Run linter
      run: |
          cd setup/dashboard || exit 1
          npm run lint

  php-linter:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 7.4

    - name: Run linter
      run: |
          composer run-script lint
    - name: Run PHPStan
      run: |
          composer run-script analyse

  shell-linter:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Run linter
      uses: azohra/shell-linter@latest
      with:
        # todo: scripts in packages
        path: "onekey.sh,setup.sh"

  python-linter:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8
          pipenv run futurize
